### ISSUE TITLE
Small typ0 and CMake build

### ISSUE THREAD

**Issue by farrer** [BazkieBumpercar/GameplayFootball#1]
First, thanks for releasing the source code, it is a great step (I hope that should help new football projects in the future).

I known you don't want to work on it, but a quick fix: at elizacontroller.cpp, line 24, there's an extra '{'.

Also, I've created a CMake configuration (both for it and for the Blunted2) for build, if you want, I can make a pull request with that (although I didn't test on anything besides linux, as I don't have a windows machine).

That's it, I do not plan to work on the code, it's just to make the compilation easier for anyone that want to try it directly by code compilation (the precompiled binary, for example, won't work for me as it depends on pulse-audio which I do not use on my Linux, thus the need to recompile to being able to run it).

Anyway, again, thanks a lot for it!

**Comment by BazkieBumpercar** [comment]
Thanks a lot man, I fixed the stray { 👍 

I have little knowledge about CMake tbh; I don't want to clutter the repo but if it's just one or two config files then I'm happy to add :) I'd say go ahead with that pull request and I'll take a look. Thanks for your help 💯

**Comment by farrer** [comment]
Pull requests created both for Blunted2 and GameplayFootball. Feel free to just discard it if you feel it's too much to add to the repository.
