### ISSUE TITLE
designatedPossessionPlayer v.s. ballRetainer

### ISSUE THREAD

**Issue by ziaoang** [BazkieBumpercar/GameplayFootball#11]
Hi BazkieBumpercar,
    In the match.cpp, there are two variates: "designatedPossessionPlayer" and "ballRetainer", it seems they are all mean the player who controll the ball. Is there some diffenence between them?
Thanks a lot~

**Comment by roberth11** [comment]
> Hola BazkieBumpercar,
> en el match.cpp, hay dos variantes: "designadoPosessionPlayer" y "ballRetainer", parece que todos son el jugador que controla la pelota. ¿Hay alguna diferencia entre ellos?
> Muchas gracias ~

you could already compile the game

**Comment by BazkieBumpercar** [comment]
I *think* ballRetainer is the player with the balls in his hands, like, the keeper.  Not 100% sure I remember correctly, though!

designatedPossessionPlayer is basically the player closest (time-wise) to the ball

**Comment by ziaoang** [comment]
Thank~
