### ISSUE TITLE
Draw text over a texture

### ISSUE THREAD

**Issue by acoppola** [BazkieBumpercar/GameplayFootball#12]
Not really an issue, but there is a way (or an idea) to draw a text (using fonts) over a rendered texture? I'd like to draw player name and shirt number on the back of the shirt. 
(Already search all over the web, so if you had same problem in the past could be very useful to share the solution, otherwise it will take some time to solve it)

**Comment by acoppola** [comment]
solved

**Comment by roberth11** [comment]
could i put the solution please thanks

**Comment by roberth11** [comment]
> resuelto

Could you share the code or where I find information from since what I found was not enough and it did not solve the problem for me and I would like to do the same, could you help me please
