### ISSUE TITLE
width depth mistake?

### ISSUE THREAD

**Issue by ziaoang** [BazkieBumpercar/GameplayFootball#14]
In src/onthepitch/teamAIcontroller.cpp
line 356 - 359
···
float backXBound = centerX - adaptedDepth * pitchHalfW * -team->GetSide();
float frontXBound = centerX + adaptedDepth * pitchHalfW * -team->GetSide();
float lowYBound = centerY - adaptedWidth * pitchHalfH;
float highYBound = centerY + adaptedWidth * pitchHalfH;
···
Is "adaptedDepth" should corresponding to "pitchHalfH" and "adaptedWidth" corresponding to "pitchHalfW"?

**Comment by BazkieBumpercar** [comment]
I don't think it's a bug, but I do think I may have used very confusing definitions. I seem to be using 'width' in one context, where the same thing is called 'height' in another context. Sorry about that :$
