### ISSUE TITLE
Making my own adaption based on this code

### ISSUE THREAD

**Issue by yassirlaaouissi** [BazkieBumpercar/GameplayFootball#17]
Hey @BazkieBumpercar 

Ik zou graag deze coole open source game willen omtoveren tot een steam game met het community systeem van de game CounterStrike: Global Offensive. Om het hele idee van FIFA "Pay to win" te elimineren. Is het okay als ik deze code neem en daarop voortborduur?

**Comment by BazkieBumpercar** [comment]
Hallo! Ik weet niet helemaal wat je bedoelt met "met het community systeem van de game CounterStrike: Global Offensive"? Daar ben ik niet mee bekend namelijk :) Ben ook benieuwd verder naar je plannen qua code; wil je er veel aan veranderen, of grofweg deze versie aanbieden op steam?

Maar either way, de code is public domain, dus je mag er alles mee doen wat je wilt :) Wees er wel van bewust dat ik geen support bied!

**Comment by yassirlaaouissi** [comment]
Hey ben ik weer. In nogal ambitieuse lijnen wil ik kijken hoe ver ik kom met het realiseren van het volgende gebaseerd op de code in deze repo:

1. Het beschikbaar stellen van multiplayer games op basis van dit spel
2. Het spel puur prestatiegericht maken, en dus niet zoals spellen zoals FIFA doen --> pay to win, koop je fifa punten met echt geld, krijg je betere spelers en win je dus veel sneller. Dit element wil ik elimineren.
3. Een community based market voor cosmetic items, hierin kunnen spelers geld investeren zonder er in het spel beter van te gaan spelen. Daarnaast moeten spelers hun cosmetic items kunnen traden en moeten community members cosmetic item designs kunne submitten. Dit is basicly was CounterStrike nu doet op steam, en het is een best wel goed systeem.
4. Een online ranking system, denk aan MMR achtige dingen.
5. Diverse multiplayer en singleplayer gamemodes.
6. Game een beetje up to spec brengen, de source code is wat oud ofcourse. Graphics waren al niet super super goed natuurlijk. Het is even aankijken hoe realistisch ik dit spel kan maken.

Dit is een hele waslijst dus het is meer dan logisch dat je hier geen support voor aanbiedt. Ik ben al super blij dat je een van de enige bent die open sourcecode hebt voor een game die ook maar iets wegheeft van een redelijk voetbal spelletje. In principe moet het uiteindelijk een gratis spel worden, ben niet van plan om er aan te verdienen. Ik heb het gevoel dat er nogal wat draagvlak is binnen de FIFA/PES community.
Thanks in ieder geval voor je verduidelijking!

**Comment by BazkieBumpercar** [comment]
Ha cool, ook bedankt voor het delen van je plannen. Klinkt allemaal vet en denk zeker dat er draagvlak voor is.
Enige is, en dat is ook de belangrijkste reden dat ik zelf ben gestopt, het gebruikt m'n eigen engine, en dat maakt alles 10x lastiger. Eigenlijk moet het geheel geport worden naar een 'echte' engine, Unity of Unreal oid, dat scheelt zoveel developmenttijd 'in the long run'. Maar dat porten lijkt me nogal een project an sich. Maar die keuze mag je zelf maken uiteraard :)

Iig, ik denk dat je niet moet onderschatten hoeveel werk eea is, maar vind het iig leuk dat je een poging wil wagen, dus wens je veel succes! Zou cool zijn als het lukt.

**Comment by yassirlaaouissi** [comment]
Ikr, dit soort dingen kunnen enorm veel tijd slurpen. Gelukkig hebben we een coronapandemie die ons lekker binnen houdt. Mijn plan is om deze zomer daar tijd aan te besteden als reizen naar het buitenland zo strikt blijft als het nu is. We zien we hoe het loopt. Zal ff kijken hoe het loopt met unity engine oid. Zou wel chill zijn om het idd daarheen te porten.

**Comment by BazkieBumpercar** [comment]
Succes!
