### ISSUE TITLE
I can't find any header files

### ISSUE THREAD

**Issue by hasanleiva** [BazkieBumpercar/GameplayFootball#5]
Hi I can't find any header files from archive.  For example, (shared_ptr.hpp , condition. hpp ) I think these files are  part of Blunted2 engine. Can you help me:)

**Comment by BazkieBumpercar** [comment]
Yes, this project also need the blunted2 engine, you can find it at https://github.com/BazkieBumpercar/Blunted2
Also, you need some c++ boost libaries.
I hope this helps :)

**Comment by acoppola** [comment]
You need to compile blunted2 engine (setup all those libraries that are required when I run cmake) as static library and then compile gameplayfootball.

**Comment by hasanleiva** [comment]
Thanks for support. I want to import or remake thjs project in Unity Game Engine. 
What do you can advice to me?

**Comment by acoppola** [comment]
Well, Unity use a different programming language. Import o remaking the project is very complex. I don't know what is your level of knowledge but you need to do things step by step. Buy a course on Udemy and some books, study them, then begin to develop simple games, then, when you are confident try to develop a football game using some of the very clever tricks that Bastian used. Developing this game took some years to him so this is not easy at all.

**Comment by BazkieBumpercar** [comment]
What @acoppola says!
Furthermore, I would use my game as 'handy guide', and maybe use some assets; not 'literally' port it.
Good luck :)

**Comment by hasanleiva** [comment]
Hi Baastian
Have you got compiled app of animationtool(blunted2)??
