### ISSUE TITLE
fastapprox.h and function curve

### ISSUE THREAD

**Issue by ziaoang** [BazkieBumpercar/GameplayFootball#8]
Hi BazkieBumpercar,
        There is a function called "curve" shows many times in the code, but I can not find its definition. It seems come from fastapprox.h, but no this file included.
        Could you give the definition of this function "curve"?
Thank you~

**Comment by BazkieBumpercar** [comment]
It's in the engine, the blunted2 project (also on github)
Here's the definition:
<code>
  inline float curve(float source, float bias = 1.0f) { // make linear / into sined _/-
    return (sin((source - 0.5f) * pi) * 0.5f + 0.5f) * bias + source * (1.0f - bias);
  }
</code>
So it will make a linear line into a nice sine curve :)

**Comment by ziaoang** [comment]
Cool, I find it in the blunted2 project~
